// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvoqsra8dJU-Vs2JBm8u4nAit_G-oOlaI',
    appId: '1:438219377922:web:4dca42ba7ab5b046ec061b',
    messagingSenderId: '438219377922',
    projectId: 'push-notification-6c99f',
    authDomain: 'push-notification-6c99f.firebaseapp.com',
    storageBucket: 'push-notification-6c99f.appspot.com',
    measurementId: 'G-SQY9CV8LW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD468gDRjWf_gvPSkIIQJ2KI21EZYSj5Iw',
    appId: '1:438219377922:android:d164e33b908e5f3cec061b',
    messagingSenderId: '438219377922',
    projectId: 'push-notification-6c99f',
    storageBucket: 'push-notification-6c99f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVOEDkgyrMqeVcqCWdRKqAq2TGvfDMx0g',
    appId: '1:438219377922:ios:a7cc4467209aadd8ec061b',
    messagingSenderId: '438219377922',
    projectId: 'push-notification-6c99f',
    storageBucket: 'push-notification-6c99f.appspot.com',
    iosBundleId: 'com.push.notify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVOEDkgyrMqeVcqCWdRKqAq2TGvfDMx0g',
    appId: '1:438219377922:ios:4d88121ec3e295a8ec061b',
    messagingSenderId: '438219377922',
    projectId: 'push-notification-6c99f',
    storageBucket: 'push-notification-6c99f.appspot.com',
    iosBundleId: 'com.example.pushNotificationApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvoqsra8dJU-Vs2JBm8u4nAit_G-oOlaI',
    appId: '1:438219377922:web:52b35aeef28e4fd1ec061b',
    messagingSenderId: '438219377922',
    projectId: 'push-notification-6c99f',
    authDomain: 'push-notification-6c99f.firebaseapp.com',
    storageBucket: 'push-notification-6c99f.appspot.com',
    measurementId: 'G-D1JPEBMTGX',
  );
}
